[package]
name = "vess-wallet"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "vess-wallet-cli"
path = "src/main.rs"

[dependencies]
vess-crypto = { path = "../vess-crypto" }
vess-network = { path = "../vess-network" }
hex = "0.4"
rand = "0.8"
heed = "0.20"
zeroize = { version = "1", features = ["derive"] }
rpassword = "7"
