@echo off
REM Gradle wrapper bootstrap for Vess Android.
REM Generated by deploy-android.ps1 setup step.

setlocal

set GRADLEW_DIR=%~dp0
set GRADLEW_JAR=%GRADLEW_DIR%gradle\wrapper\gradle-wrapper.jar
set GRADLEW_PROPS=%GRADLEW_DIR%gradle\wrapper\gradle-wrapper.properties

REM ── Download gradle-wrapper.jar if missing ────────────────────
if exist "%GRADLEW_JAR%" goto :run

echo.
echo [setup] Downloading Gradle wrapper...
echo.

REM Read distribution URL from properties file to get version
for /f "tokens=2 delims==" %%a in ('findstr "distributionUrl" "%GRADLEW_PROPS%"') do (
    set GRADLE_URL=%%a
)
REM Extract version from URL (e.g. gradle-8.11.1-bin.zip → 8.11.1)
for /f "tokens=2 delims=-" %%a in ("%GRADLE_URL%") do (
    for /f "tokens=1 delims=." %%b in ("%%a") do set GRADLE_MAJOR=%%b
)

REM Default wrapper jar version — matches 8.x series
set WRAPPER_JAR_URL=https://raw.githubusercontent.com/gradle/gradle/v8.11.1/gradle/wrapper/gradle-wrapper.jar

echo Downloading gradle-wrapper.jar...
powershell -Command "Invoke-WebRequest -Uri '%WRAPPER_JAR_URL%' -OutFile '%GRADLEW_JAR%'" 2>nul

if not exist "%GRADLEW_JAR%" (
    echo.
    echo ERROR: Could not download gradle-wrapper.jar.
    echo.
    echo To fix this manually:
    echo   1. Open this project in Android Studio once ^(File → Open → vess-android^)
    echo   2. Or install Gradle and run: cd vess-android ^&^& gradle wrapper
    echo.
    exit /b 1
)

echo gradle-wrapper.jar downloaded.

:run
REM ── Find Java ─────────────────────────────────────────────────
set JAVA_EXE=
if exist "%JAVA_HOME%\bin\java.exe" (
    set JAVA_EXE=%JAVA_HOME%\bin\java.exe
) else (
    for /f "tokens=*" %%i in ('where java 2^>nul') do (
        set JAVA_EXE=%%i
        goto :found_java
    )
)
:found_java

if "%JAVA_EXE%"=="" (
    echo ERROR: Java not found. Install Java 17+ and set JAVA_HOME.
    exit /b 1
)

REM ── Run Gradle ───────────────────────────────────────────────
set GRADLE_OPTS=-Dorg.gradle.appname=gradlew -Xmx2048m
"%JAVA_EXE%" %GRADLE_OPTS% -classpath "%GRADLEW_JAR%" org.gradle.wrapper.GradleWrapperMain %*

endlocal & exit /b %ERRORLEVEL%
