[package]
name = "vess-artery"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[[bin]]
name = "vess-artery"
path = "src/main.rs"

[features]
test-pow = ["vess-tag/test-pow"]
test-mint = ["vess-foundry/test-mint"]

[dependencies]
hex = "0.4"
vess-mesh = { path = "../vess-mesh" }
vess-stealth = { path = "../vess-stealth" }
vess-foundry = { path = "../vess-foundry" }
vess-protocol = { path = "../vess-protocol" }
vess-tag = { path = "../vess-tag" }
vess-sovereign = { path = "../vess-sovereign" }
argon2 = "0.5"
blake3 = "1"
cuckoofilter = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["alloc"] }
dirs-next = "2"
socket2 = "0.5"
rand = "0.8"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
zeroize = { version = "1", features = ["zeroize_derive"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Threading"] }
ipconfig = "0.3"

[build-dependencies]
blake3 = "1"

[dev-dependencies]
proptest = "1"
tempfile = "3"
vess-tag = { path = "../vess-tag", features = ["test-pow"] }
