[package]
name = "vess-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.10"
alloy-sol-types = "1"
vess-crypto = { path = "../vess-crypto", default-features = false, features = ["verify"] }
getrandom = { version = "0.2", features = ["js"] }
getrandom-04 = { package = "getrandom", version = "0.4", features = ["wasm_js"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
